In [3]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('large_student_dataset.csv')
subdata = dataset.head(50)
X = subdata.iloc[:, 2:6].values
y = subdata.iloc[:, -1].values
print(X)

# Encoding categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Training the Multiple Linear Regression model on the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[ 94.          96.          62.          84.        ]
 [ 97.          99.          52.          82.66666667]
 [ 50.          74.          66.          63.33333333]
 [ 53.          90.          87.          76.66666667]
 [ 53.          72.          71.          65.33333333]
 [ 89.         100.          88.          92.33333333]
 [ 59.          79.          89.          75.66666667]
 [ 69.          90.          59.          72.66666667]
 [ 71.          95.          75.          80.33333333]
 [100.         100.          98.          99.33333333]
 [ 86.          66.          64.          72.        ]
 [ 73.          89.          63.          75.        ]
 [ 56.          61.         100.          72.33333333]
 [ 74.          82.          96.          84.        ]
 [ 74.          90.          97.          87.        ]
 [ 62.          77.          59.          66.        ]
 [ 51.          62.          76.          63.        ]
 [ 88.          64.          98.          83.33333333]
 [ 89.    

TypeError: Singleton array array(<50x43 sparse matrix of type '<class 'numpy.float64'>'
	with 200 stored elements in Compressed Sparse Row format>, dtype=object) cannot be considered a valid collection.