# Numpy Concept

In [2]:
#Simple Arrray in Python

import numpy as np

arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


Finding Size Of Array Using Np

In [9]:
#Finding Size Of Array Using Np
#import numpy as np

arr=np.array([1,2,3,4])
print(arr)
np.size(arr)

[1 2 3 4]


4

Find Shape Of Array

In [11]:
#Finding Shape Of Array 1-Dimensional

arr=np.array([1,2,3,4])
print(arr)
np.shape(arr)

[1 2 3 4]


(4,)

In [14]:
#Finding Shape Of Array 2-Dimensional

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
np.shape(arr)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

Finding DataType Of Array

In [15]:
#Finding DataType Of Array

arr=np.array([1,2,3,4])
print(arr)
arr.dtype

[1 2 3 4]


dtype('int32')

# Operations

In [23]:
#simple Operation +,-,* For Each element in list

arr=np.array([1,2,3,4])
print("Normal Array Is    : ",arr)
print("Increment Array Is : ",arr+2)
print("Decrement Array Is : ",arr-2)
print("Multiplyed Array Is : ",arr*2)

Normal Array Is    :  [1 2 3 4]
Increment Array Is :  [3 4 5 6]
Decrement Array Is :  [-1  0  1  2]
Multiplyed Array Is :  [2 4 6 8]


Mathematical Operation

In [35]:
#Mathematical Operation of Finding Sum

arr=np.array([1,2,3,4])
print("Normal Array : ",arr)
s=np.sum(arr)
print("Sum Of Array :",s)

Normal Array :  [1 2 3 4]
Sum Of Array : 10


In [37]:
#Mathematical Operation Of Finding Mean

arr=np.array([1,2,3,4])
print("Normal Array : ",arr)
m=np.mean(arr)
print("Mean Of Array :",m)

Normal Array :  [1 2 3 4]
Mean Of Array : 2.5


In [38]:
#Mathematical Operation Of Finding Standard Deviation

arr=np.array([1,2,3,4])
print("Normal Array : ",arr)
s=np.std(arr)
print("Standard deviation Of Array :",s)

Normal Array :  [1 2 3 4]
Standard deviation Of Array : 1.118033988749895


# Indexing

In [33]:
#print direct index which ever we want

arr=np.array([1,2,3,4])
print("Normal Array : ",arr)
arr[3]

Normal Array :  [1 2 3 4]


4

# Slicing

In [39]:
#If we want to print from index 0 to 3 then we use slicing concept

arr=np.array([1,2,3,4])
print("Normal Array : ",arr)
arr[1:3]

Normal Array :  [1 2 3 4]


array([2, 3])

# Matrix Operation

In [46]:
#If we want to add two matrix

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[5,6,],[3,4],[8,5]])
print("First Array:\n",arr1)
print("Second Array:\n",arr2)
add=np.dot(arr1,arr2)
print("Multiplication Of Array\n",add)

First Array:
 [[1 2 3]
 [4 5 6]]
Second Array:
 [[5 6]
 [3 4]
 [8 5]]
Multiplication Of Array
 [[35 29]
 [83 74]]


# Random Module

In [48]:
#random input 

arr=np.array(np.random.rand(3))
print("Random Array:\n",arr)

Random Array:
 [0.89201906 0.78897426 0.78865956]


In [53]:
#Random input in INTEGER Type

arr=np.array(np.random.randint(1,3,5))
print("Random Number In Integer Format:\n",arr)

Random Number In Integer Format:
 [2 1 2 2 2]
